---
abstract: 'a software model for a set of collated texts'
author:
  - 'Tara L Andrews <aurum@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.56
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Tradition
name: Text-Tradition
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 0
  Bio::Phylo::IO: 0
  File::chdir: 0
  Graph: 0
  Graph::Convert: 0
  Graph::Easy: 0
  Graph::Reader::Dot: 0
  IPC::Run: 0
  Module::Load: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::NonMoose: 0
  Text::CSV::Simple: 0
  Text::CSV_XS: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  perl: 5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
